# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Install Dependancy'

- script: |
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20210702/codeql-runner-linux
    chmod +x codeql-runner-linux
  displayName: 'Get Latest CodeQl and Install Agent.'

- script: |
    ./codeql-runner-linux init \
    --repository ankitosh/sample-java-programs \
    --github-url https://github.com \
    --github-auth $(GITHUB)
  displayName: 'Initialize CodeQl and Install Agent.'

- script: gitleaks --config=.gitleaks.toml --repo-path=$(Build.Repository.LocalPath) --verbose --redact
  displayName: 'Scan Code for Static Credentials'

- script: |
    ./codeql-runner-linux analyze \
    --repository ankitosh/sample-java-programs \
    --github-url https://github.com \
    --github-auth $(GITHUB) \
    --commit $(Build.SourceVersion) \
    --ref $(Build.SourceBranch)
  displayName: 'Build Analyze and upload the code '